name: Update Proxy IP Statusbisa

on:
  schedule:
    - cron: '0 0 */7 * *'  # Pengecekan setiap 7 hari sekali
  workflow_dispatch:  # Memungkinkan untuk menjalankan secara manual

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    # Langkah pertama: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Langkah kedua: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Langkah ketiga: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Langkah keempat: Memeriksa keberadaan file input
    - name: Check if totalproxylist.txt exists
      run: |
        if [ -f totalproxylist.txt ]; then
          echo "File totalproxylist.txt ditemukan."
        else
          echo "File totalproxylist.txt tidak ditemukan. Workflow dihentikan."
          exit 1  # Keluar jika file tidak ditemukan
        fi

    # Langkah kelima: Update proxy status
    - name: Update proxy status
      env:
        IP_FILE: 'totalproxylist.txt'  # Ganti dengan nama file input proxy kamu
        API_URL: 'https://proxyip-check.vercel.app/{ip}:{port}'  # Ganti dengan API endpoint yang kamu pakai
      run: |
        python update_proxy_status.py  # Jalankan skrip Python yang sudah kamu buat

    # Langkah keenam: Commit dan push perubahan
    - name: Check if there are changes to commit
      run: |
        git status  # Memastikan ada perubahan file
        git diff --cached  # Memeriksa perbedaan yang akan di-commit

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add totalproxylist.txt  # Menambahkan file proxy yang diperbarui
        git add error.txt  # Menambahkan file error log
        git add kvProxylist.json  # Menambahkan file kvProxylist.json
        git add alive_proxies_grouped.json  # Menambahkan file alive_proxies_grouped.json
        git add active_proxies.csv  # Menambahkan file active_proxies.csv
        if git diff --cached --exit-code; then
          echo "Tidak ada perubahan untuk di-commit"
        else
          git commit -m "Update proxy IP status and JSON grouping"
          git push
        fi
