name: Update Proxy IP Status21

on:
  schedule:
    - cron: '0 0 */7 * *'  # Pengecekan setiap 7 hari sekali
  workflow_dispatch:  # Memungkinkan untuk menjalankan secara manual

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Debugging: Check file structure
      run: |
        ls -alh  # Melihat struktur folder di runner
        python --version  # Memastikan Python tersedia
        python -m pip show requests  # Memastikan dependencies terinstal

    - name: Update proxy status
      env:
        IP_FILE: 'proxy_list.csv'  # Ganti dengan nama file input proxy kamu
        API_URL: 'https://proxyip-check.vercel.app/{ip}:{port}'  # Ganti dengan API endpoint yang kamu pakai
      run: |
        python scripts/update_proxy_status.py  # Path yang benar jika ada di folder 'scripts'

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add proxy_list.csv  # Menambahkan file proxy yang diperbarui
        git add error.txt  # Menambahkan file error log
        git add kvProxylist.json  # Menambahkan file kvProxylist.json
        git add alive_proxies_grouped.json  # Menambahkan file alive_proxies_grouped.json
        git add active_proxies.csv  # Menambahkan file active_proxies.csv
        if git diff --cached --exit-code; then
          echo "No changes to commit"
        else
          git commit -m "Update proxy IP status and JSON grouping"
          git push
        fi
